# Generated by Django 2.0 on 2018-04-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='菜单名称')),
                ('flag_use', models.BooleanField(default=True, verbose_name='启用')),
                ('na_par', models.CharField(max_length=30, verbose_name='上级名称')),
            ],
        ),
    ]
