# Generated by Django 2.0 on 2018-05-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleId', models.UUIDField(default='60a10988-5d6c-11e8-851f-44032cf9b14e', verbose_name='主键')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('category', models.PositiveIntegerField(default=0, verbose_name='类型')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='发布日期')),
                ('show', models.BooleanField(default=True, verbose_name='展示')),
                ('visits', models.PositiveIntegerField(default=0, verbose_name='阅读量')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('keyword', models.CharField(default='', max_length=100, verbose_name='关键字')),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='名称')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('path', models.CharField(max_length=255, verbose_name='路径')),
                ('stem_from', models.CharField(max_length=255, verbose_name='来源')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(default='', max_length=30, verbose_name='名称')),
                ('flag_use', models.BooleanField(default=True, verbose_name='启用')),
                ('code', models.IntegerField(default=0, verbose_name='编码')),
                ('na_par', models.CharField(max_length=30, verbose_name='上级')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='发布日期')),
            ],
        ),
    ]
