# Generated by Django 2.0 on 2018-05-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articleId',
            field=models.UUIDField(default='a243c262-5d6c-11e8-817d-44032cf9b14e', verbose_name='主键'),
        ),
    ]
