# Generated by Django 2.0 on 2018-05-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180430_0719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('category', models.PositiveIntegerField(max_length=10, verbose_name='类型')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='发布日期')),
                ('show', models.BooleanField(default=True, verbose_name='展示')),
                ('visits', models.PositiveIntegerField(default=0, verbose_name='阅读量')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
