# Generated by Django 2.0 on 2018-05-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='code',
            field=models.IntegerField(default=0, verbose_name='编码'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.PositiveIntegerField(default=0, verbose_name='类型'),
        ),
    ]
