# Generated by Django 2.0 on 2018-05-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180502_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='name',
        ),
        migrations.AddField(
            model_name='menu',
            name='caption',
            field=models.CharField(default='', max_length=30, verbose_name='名称'),
        ),
    ]
