# Generated by Django 2.0 on 2018-05-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180502_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='名称')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('path', models.CharField(max_length=255, verbose_name='路径')),
                ('stem_from', models.CharField(max_length=255, verbose_name='来源')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='keyword',
            field=models.CharField(default='', max_length=100, verbose_name='关键字'),
        ),
    ]
